/**
 * @packageDocumentation
 * @module api.functional.workers
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";

import type { ApproveWorkerBody } from "../../structures/ApproveWorkerBody";
import type { DiscoveredWorkerHTTP } from "../../structures/DiscoveredWorkerHTTP";
import type { ServerHTTP } from "../../structures/ServerHTTP";

/**
 * @controller DiscoverWorkersController.discover
 * @path GET /workers
 * @accessor api.functional.workers.discover
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function discover(
  connection: IConnection,
): Promise<discover.Output> {
  return PlainFetcher.fetch(connection, {
    ...discover.METADATA,
    template: discover.METADATA.path,
    path: discover.path(),
  });
}
export namespace discover {
  export type Output = DiscoveredWorkerHTTP[];

  export const METADATA = {
    method: "GET",
    path: "/workers",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/workers";
}

/**
 * @controller ApproveWorkerController.approve
 * @path POST /workers/approve
 * @accessor api.functional.workers.approve
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function approve(
  connection: IConnection,
  body: approve.Body,
): Promise<approve.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...approve.METADATA,
      template: approve.METADATA.path,
      path: approve.path(),
    },
    body,
  );
}
export namespace approve {
  export type Body = ApproveWorkerBody;
  export type Output = ServerHTTP.o1;

  export const METADATA = {
    method: "POST",
    path: "/workers/approve",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/workers/approve";
}
