/**
 * @packageDocumentation
 * @module api.functional.servers
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";

import type { ServerHTTP } from "../../structures/ServerHTTP";

/**
 * @controller FetchServersController.fetch
 * @path GET /servers
 * @accessor api.functional.servers.fetch
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function fetch(connection: IConnection): Promise<fetch.Output> {
  return PlainFetcher.fetch(connection, {
    ...fetch.METADATA,
    template: fetch.METADATA.path,
    path: fetch.path(),
  });
}
export namespace fetch {
  export type Output = ServerHTTP[];

  export const METADATA = {
    method: "GET",
    path: "/servers",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/servers";
}
