/**
 * @packageDocumentation
 * @module api.functional.servers
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { tags } from "typia";

import type { RegisterServerBody } from "../../structures/RegisterServerBody";
import type { ServerHTTP } from "../../structures/ServerHTTP";

/**
 * @controller RegisterServerController.register
 * @path POST /servers
 * @accessor api.functional.servers.register
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function register(
	connection: IConnection,
	body: register.Body,
): Promise<register.Output> {
	return PlainFetcher.fetch(
		{
			...connection,
			headers: {
				...connection.headers,
				"Content-Type": "application/json",
			},
		},
		{
			...register.METADATA,
			template: register.METADATA.path,
			path: register.path(),
		},
		body,
	);
}
export namespace register {
	export type Body = RegisterServerBody;
	export type Output = ServerHTTP;

	export const METADATA = {
		method: "POST",
		path: "/servers",
		request: {
			type: "application/json",
			encrypted: false,
		},
		response: {
			type: "application/json",
			encrypted: false,
		},
		status: 201,
	} as const;

	export const path = () => "/servers";
}

/**
 * @controller HeartbeatServerController.heartbeat
 * @path PATCH /servers/:id
 * @accessor api.functional.servers.heartbeat
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function heartbeat(
	connection: IConnection,
	id: string & tags.Format<"uuid">,
): Promise<heartbeat.Output> {
	return PlainFetcher.fetch(connection, {
		...heartbeat.METADATA,
		template: heartbeat.METADATA.path,
		path: heartbeat.path(id),
	});
}
export namespace heartbeat {
	export type Output = ServerHTTP.o1;

	export const METADATA = {
		method: "PATCH",
		path: "/servers/:id",
		request: null,
		response: {
			type: "application/json",
			encrypted: false,
		},
		status: 200,
	} as const;

	export const path = (id: string & tags.Format<"uuid">) =>
		`/servers/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller FetchServersController.fetch
 * @path GET /servers
 * @accessor api.functional.servers.fetch
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function fetch(connection: IConnection): Promise<fetch.Output> {
	return PlainFetcher.fetch(connection, {
		...fetch.METADATA,
		template: fetch.METADATA.path,
		path: fetch.path(),
	});
}
export namespace fetch {
	export type Output = ServerHTTP.o2[];

	export const METADATA = {
		method: "GET",
		path: "/servers",
		request: null,
		response: {
			type: "application/json",
			encrypted: false,
		},
		status: 200,
	} as const;

	export const path = () => "/servers";
}
