/**
 * @packageDocumentation
 * @module api.functional.applications
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";

import type { ApplicationHTTP } from "../../structures/ApplicationHTTP";
import type { CreateApplicationBody } from "../../structures/CreateApplicationBody";

/**
 * @controller FetchApplicationsController.fetch
 * @path GET /applications
 * @accessor api.functional.applications.fetch
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function fetch(connection: IConnection): Promise<fetch.Output> {
  return PlainFetcher.fetch(connection, {
    ...fetch.METADATA,
    template: fetch.METADATA.path,
    path: fetch.path(),
  });
}
export namespace fetch {
  export type Output = ApplicationHTTP[];

  export const METADATA = {
    method: "GET",
    path: "/applications",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/applications";
}

/**
 * @controller CreateApplicationController.create
 * @path POST /applications
 * @accessor api.functional.applications.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    body,
  );
}
export namespace create {
  export type Body = CreateApplicationBody;
  export type Output = ApplicationHTTP.o1;

  export const METADATA = {
    method: "POST",
    path: "/applications",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/applications";
}
