/**
 * @packageDocumentation
 * @module api.functional.canvas
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import type { Driver } from "tgrid";
import { WebSocketConnector } from "tgrid";

import type {
  CanvasListener,
  CanvasProvider,
} from "../../../../../apps/api/src/infra/http/controllers/canvas.protocol";

/**
 * @controller CanvasController.connect
 * @path /canvas
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function connect(
  connection: IConnection<connect.Header>,
  provider: connect.Provider,
): Promise<connect.Output> {
  const url: string = `${connection.host.endsWith("/") ? connection.host.substring(0, connection.host.length - 1) : connection.host}${connect.path()}`;
  const connector: WebSocketConnector<
    connect.Header,
    connect.Provider,
    connect.Listener
  > = new WebSocketConnector(
    connection.headers ?? ({} as connect.Header),
    provider,
  );
  await connector.connect(url);
  const driver: Driver<connect.Listener> = connector.getDriver();
  return {
    connector,
    driver,
    reconnect: async () => await connector.connect(url),
  };
}
export namespace connect {
  export type Output = {
    connector: WebSocketConnector<Header, Provider, Listener>;
    driver: Driver<Listener>;
    reconnect: () => Promise<void>;
  };
  export type Header = object;
  export type Provider = CanvasListener;
  export type Listener = CanvasProvider;

  export const path = () => "/canvas";
}
